<script setup lang="ts">
definePageMeta({ middleware: 'auth' })
const { locale, t } = useLocale()
const open = ref(1)
const steps = computed(() => locale.value === 'lo' ? [
  { icon:'mdi-facebook', title:'1. ເຊື່ອມ Facebook Page', summary:'ໃຫ້ສະຖານະ Page ແລະ Webhook ເປັນສີຂຽວ', details:['ໄປທີ່ ເພຈ ແລະ WhatsApp','ກົດ Connect Facebook ແລະອະນຸຍາດ pages_messaging','ເປີດ Page ທີ່ຕ້ອງການ ແລ້ວກວດ Webhook status'] },
  { icon:'mdi-package-variant-closed', title:'2. ສ້າງສິນຄ້າ', summary:'ເກັບຊື່, ລາຄາ ແລະລາຍລະອຽດໄວ້ໃຊ້ໃນຄຳຕອບ', details:['ໄປທີ່ ສິນຄ້າ','ເພີ່ມຊື່, ລາຄາ, ລາຍລະອຽດ ແລະຮູບ','ບັນທຶກແລ້ວກວດຕົວຢ່າງ'] },
  { icon:'mdi-message-text-fast-outline', title:'3. ສ້າງຊຸດຂໍ້ຄວາມ', summary:'ຈັດລຳດັບ text, image, video ຫຼື audio', details:['ໄປທີ່ ຊຸດຂໍ້ຄວາມ','ເພີ່ມຂໍ້ຄວາມ ຫຼື media ຕາມລຳດັບ','ປິດລາຍການທີ່ຍັງບໍ່ຢາກສົ່ງ'] },
  { icon:'mdi-robot-happy-outline', title:'4. ສ້າງ Automation', summary:'ຜູກ Page + ໂພສ/Campaign + ສິນຄ້າ + ຊຸດຂໍ້ຄວາມ', details:['ຕັ້ງຊື່ ແລະເລືອກ Page','ເລືອກໂພສ ຫຼື Campaign ໄດ້ຫຼາຍລາຍການ','ເລືອກສິນຄ້າ ແລະຊຸດຂໍ້ຄວາມ','ໃຊ້ First message only ເພື່ອບໍ່ໃຫ້ຕອບຊ້ຳ'] },
  { icon:'mdi-flask-outline', title:'5. ທົດສອບກ່ອນໃຊ້ຈິງ', summary:'ສົ່ງ 1 ຂໍ້ຄວາມ ແລະກວດ log/ລຳດັບຄຳຕອບ', details:['ເປີດ Automation ແລະສົ່ງຂໍ້ຄວາມຈາກ user ທົດສອບ','ກວດວ່າສົ່ງພຽງຄັ້ງດຽວ ແລະລຳດັບຖືກຕ້ອງ','ຖ້າບໍ່ສົ່ງ ໃຫ້ກວດ Page, Webhook, permission ແລະ Automation status'] },
] : [
  { icon:'mdi-facebook', title:'1. Connect a Facebook Page', summary:'Make sure the Page and Webhook statuses are green.', details:['Open Pages & WhatsApp','Connect Facebook and allow pages_messaging','Enable the Page and verify its Webhook status'] },
  { icon:'mdi-package-variant-closed', title:'2. Create a Product', summary:'Save product details used by replies.', details:['Open Products','Add name, price, details and image','Save and review the preview'] },
  { icon:'mdi-message-text-fast-outline', title:'3. Build a Reply Set', summary:'Arrange text, image, video or audio in order.', details:['Open Reply Sets','Add messages and media in send order','Disable anything that should not send'] },
  { icon:'mdi-robot-happy-outline', title:'4. Create an Automation', summary:'Connect Page, targets, Product and Reply Set.', details:['Name it and select a Page','Select multiple Posts or Campaigns','Choose Product and Reply Set','Use First message only to prevent duplicates'] },
  { icon:'mdi-flask-outline', title:'5. Test before launch', summary:'Send one message and verify logs and reply order.', details:['Enable it and send from a test user','Verify one reply and correct order','If it fails, check Page, Webhook, permissions and status'] },
])
</script>

<template>
  <section class="guide-hero"><div><small>GETTING STARTED</small><h2>{{ t('guide.title') }}</h2><p>{{ t('guide.subtitle') }}</p></div><v-btn color="primary" to="/auto-replies" prepend-icon="mdi-plus">{{ t('auto.new') }}</v-btn></section>
  <section class="guide-layout">
    <aside><strong>{{ locale==='lo'?'ກ່ອນເລີ່ມ':'Before you start' }}</strong><ul><li>Facebook Page connected</li><li>Webhook active</li><li>pages_messaging permission</li><li>{{ locale==='lo'?'ມີສິນຄ້າ ແລະຊຸດຂໍ້ຄວາມ':'A Product and Reply Set' }}</li></ul><v-alert type="info" variant="tonal" density="compact">{{ locale==='lo'?'ແນະນຳ: ທົດສອບກັບ 1 Page ແລະ 1 Post ກ່ອນ':'Tip: test with one Page and one Post first.' }}</v-alert></aside>
    <main><article v-for="(item,index) in steps" :key="item.title" :class="{open:open===index+1}"><button @click="open=open===index+1?0:index+1"><span><v-icon :icon="item.icon"/></span><div><strong>{{ item.title }}</strong><small>{{ item.summary }}</small></div><v-icon :icon="open===index+1?'mdi-chevron-up':'mdi-chevron-down'"/></button><div v-if="open===index+1" class="details"><ol><li v-for="detail in item.details" :key="detail">{{ detail }}</li></ol><div class="step-link"><v-btn v-if="index===0" to="/meta-pages" variant="tonal">{{ locale==='lo'?'ໄປຈັດການ Page':'Manage Pages' }}</v-btn><v-btn v-else-if="index===1" to="/products" variant="tonal">{{ t('nav.products') }}</v-btn><v-btn v-else-if="index===2" to="/replies" variant="tonal">{{ t('nav.replies') }}</v-btn><v-btn v-else-if="index===3" to="/auto-replies" color="primary">{{ t('auto.new') }}</v-btn></div></div></article></main>
  </section>
</template>

<style scoped>
.guide-hero{display:flex;justify-content:space-between;align-items:center;gap:20px;margin-bottom:16px;padding:26px;background:linear-gradient(135deg,var(--color-surface),var(--color-primary-soft));border:1px solid var(--color-border);border-radius:var(--radius-lg)}.guide-hero small{color:var(--color-primary);font-size:10px;font-weight:850;letter-spacing:.13em}.guide-hero h2{margin:5px 0;font-size:clamp(24px,3vw,34px)}.guide-hero p{margin:0;color:var(--color-text-secondary)}.guide-layout{display:grid;grid-template-columns:minmax(220px,.34fr) minmax(0,1fr);gap:16px}.guide-layout aside{align-self:start;position:sticky;top:20px;padding:20px;background:var(--color-surface);border:1px solid var(--color-border);border-radius:var(--radius-lg)}.guide-layout aside ul{padding-left:20px;color:var(--color-text-secondary);font-size:13px;line-height:1.9}.guide-layout main{display:grid;gap:10px}.guide-layout article{background:var(--color-surface);border:1px solid var(--color-border);border-radius:var(--radius-lg);overflow:hidden}.guide-layout article.open{border-color:color-mix(in srgb,var(--color-primary) 35%,var(--color-border));box-shadow:0 8px 24px rgba(31,35,75,.06)}.guide-layout article>button{width:100%;min-height:84px;display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:14px;padding:16px 18px;border:0;background:none;text-align:left;color:var(--color-text);cursor:pointer}.guide-layout article>button>span{width:46px;height:46px;display:grid;place-items:center;color:var(--color-primary);background:var(--color-primary-soft);border-radius:13px}.guide-layout article>button>div{display:grid;gap:4px}.guide-layout article>button strong{font-size:15px}.guide-layout article>button small{color:var(--color-text-secondary);font-size:12px}.details{padding:0 20px 20px 78px;border-top:1px solid var(--color-border-subtle)}.details ol{padding-left:20px;color:var(--color-text-secondary);font-size:13px;line-height:1.9}.step-link{display:flex;justify-content:flex-end}@media(max-width:800px){.guide-layout{grid-template-columns:1fr}.guide-layout aside{position:static}.details{padding-left:20px}}@media(max-width:640px){.guide-hero{align-items:stretch;display:grid;padding:20px}.guide-hero :deep(.v-btn){width:100%}.guide-layout article>button{grid-template-columns:auto 1fr;min-height:76px;padding:14px}.guide-layout article>button>:last-child{display:none}}
</style>
