<script setup lang="ts">
definePageMeta({ middleware: 'auth' })
interface MetaPage { id:string; name:string; connected:boolean }
interface MetaPost { id:string; message:string; createdTime:string; permalinkUrl:string; pictureUrl?:string }
interface AdAccount { id:string; name:string; accountStatus:number; accountType:'personal'|'business'; businessId?:string; businessName?:string }
interface Campaign { id:string; name:string; status:string; effectiveStatus:string; objective:string; adSetCount:number; adCount:number }
interface MetaAd { id:string; name:string; status:string; effectiveStatus:string }
interface Product { id:string; name:string; price:string; description:string }
interface ReplyStep { code:string; type:'text'|'image'|'video'|'audio'; content:string; enabled:boolean }
interface ReplyFlow { id:string; name:string; keywords:string[]; messages:ReplyStep[] }
interface Binding { pageId:string; sourceId:string; sourceType:'post'|'ad'; productId:string; flowId:string; productName:string; price:string; description:string }
const { can } = useAuth()
if (!can('pages:read')) throw createError({ statusCode:403, statusMessage:'You do not have permission to view Product Automation.' })
const { data:pageData } = await useApi<{items:MetaPage[]}>('/proxy/api/v1/meta/pages')
const { data:productData, refresh:refreshProducts } = await useApi<{items:Product[]}>('/proxy/api/v1/products')
const { data:flowData, refresh:refreshFlows } = await useApi<{items:ReplyFlow[]}>('/proxy/api/v1/reply-flows')
const { data:bindingData, refresh:refreshBindings } = await useApi<{items:Binding[]}>('/proxy/api/v1/meta/product-bindings')
const pages = computed(() => pageData.value?.items.filter(page => page.connected) || [])
const products = computed(() => productData.value?.items || [])
const flows = computed(() => flowData.value?.items || [])
const bindings = computed(() => bindingData.value?.items || [])
const pageId = ref(pages.value[0]?.id || '')
const productId = ref('')
const flowId = ref('')
const selectedPosts = ref<string[]>([])
const triggerType=ref<'post'|'ad'>('post');const adAccounts=ref<AdAccount[]>([]);const campaigns=ref<Campaign[]>([]);const ads=ref<MetaAd[]>([]);const adAccountId=ref('');const campaignId=ref('');const selectedCampaignIds=ref<string[]>([]);const selectedAds=ref<string[]>([]);const loadingAds=ref(false)
const posts = ref<MetaPost[]>([])
const loadingPosts = ref(false)
const saving = ref(false)
const productDialog = ref(false)
const flowDialog = ref(false)
const notice = ref('')
const noticeType = ref<'success'|'error'>('success')
const currentStep=ref(1)
const productForm = reactive<Product>({ id:'', name:'', price:'', description:'' })
const flowForm = reactive<ReplyFlow>({ id:'', name:'', keywords:[], messages:[{code:'message_1',type:'text',content:'',enabled:true}] })
const messageTypes=[{title:'Text',value:'text'},{title:'Image',value:'image'},{title:'Video',value:'video'},{title:'Audio',value:'audio'}]
const selectedProduct = computed(() => products.value.find(item => item.id === productId.value))
const selectedCount=computed(()=>triggerType.value==='post'?selectedPosts.value.length:selectedAds.value.length)
const adAccountOptions=computed(()=>adAccounts.value.map(account=>({...account,displayName:`${account.accountType==='business'?'Business':'Personal'} · ${account.name}`})))
const selectedAdAccount=computed(()=>adAccounts.value.find(account=>account.id===adAccountId.value))
const selectedFlow=computed(()=>flows.value.find(flow=>flow.id===flowId.value))
const stepReady=computed(()=>currentStep.value===1?Boolean(pageId.value&&selectedCount.value):currentStep.value===2?Boolean(productId.value):currentStep.value===3?Boolean(flowId.value):true)
function nextStep(){if(stepReady.value&&currentStep.value<4)currentStep.value++}
function previousStep(){if(currentStep.value>1)currentStep.value--}
function bindingFor(postId:string) { return bindings.value.find(item => item.pageId === pageId.value && item.sourceType === 'post' && item.sourceId === postId) }
async function loadPosts() {
  if (!pageId.value) return
  loadingPosts.value = true; notice.value = ''; selectedPosts.value = []
  try { posts.value = (await $fetch<{items:MetaPost[]}>(`/api/proxy/api/v1/meta/pages/${pageId.value}/posts`)).items }
  catch (error:any) { noticeType.value = 'error'; notice.value = error?.data?.message || 'Unable to load Facebook posts.' }
  finally { loadingPosts.value = false }
}
async function loadAdAccounts(){loadingAds.value=true;notice.value='';try{adAccounts.value=(await $fetch<{items:AdAccount[]}>('/api/proxy/api/v1/meta/ad-accounts')).items;if(!adAccountId.value)adAccountId.value=adAccounts.value[0]?.id||''}catch(error:any){noticeType.value='error';notice.value=error?.data?.message||'Unable to load ad accounts. Reconnect Facebook with ads_read permission.'}finally{loadingAds.value=false}}
async function loadCampaigns(){if(!adAccountId.value)return;loadingAds.value=true;campaigns.value=[];campaignId.value='';selectedCampaignIds.value=[];ads.value=[];selectedAds.value=[];try{campaigns.value=(await $fetch<{items:Campaign[]}>(`/api/proxy/api/v1/meta/ad-accounts/${adAccountId.value}/campaigns`)).items}catch(error:any){noticeType.value='error';notice.value=error?.data?.message||'Unable to load campaigns.'}finally{loadingAds.value=false}}
async function toggleCampaign(id:string){const selected=selectedCampaignIds.value.includes(id);selectedCampaignIds.value=selected?selectedCampaignIds.value.filter(item=>item!==id):[...selectedCampaignIds.value,id];campaignId.value=id;loadingAds.value=true;try{const results=await Promise.all(selectedCampaignIds.value.map(campaign=>$fetch<{items:MetaAd[]}>(`/api/proxy/api/v1/meta/campaigns/${campaign}/ads`)));const unique=new Map<string,MetaAd>();results.flatMap(result=>result.items).forEach(ad=>unique.set(ad.id,ad));ads.value=[...unique.values()];selectedAds.value=ads.value.map(ad=>ad.id)}catch(error:any){noticeType.value='error';notice.value=error?.data?.message||'Unable to load campaign ads.'}finally{loadingAds.value=false}}
function newProduct() { Object.assign(productForm, { id:'', name:'', price:'', description:'' }); productDialog.value = true }
function newFlow() { Object.assign(flowForm, { id:'', name:'', keywords:[], messages:[{code:'message_1',type:'text',content:'',enabled:true}] }); flowDialog.value = true }
function addMessage(){flowForm.messages.push({code:`message_${flowForm.messages.length+1}`,type:'text',content:'',enabled:true})}
function moveMessage(index:number, direction:number) { const target=index+direction; if(target<0||target>=flowForm.messages.length)return; const value=flowForm.messages[index]!; flowForm.messages[index]=flowForm.messages[target]!; flowForm.messages[target]=value }
async function saveFlow() {
  saving.value=true
  try { const result=await $fetch<{item:ReplyFlow}>('/api/proxy/api/v1/reply-flows',{method:'POST',body:flowForm}); await refreshFlows(); flowId.value=result.item.id; flowDialog.value=false; noticeType.value='success'; notice.value='Reply sequence saved.' }
  catch(error:any){noticeType.value='error';notice.value=error?.data?.message||'Unable to save reply sequence.'} finally{saving.value=false}
}
async function saveProduct() {
  saving.value = true
  try {
    const result = await $fetch<{item:Product}>('/api/proxy/api/v1/products', { method:'POST', body:productForm })
    await refreshProducts(); productId.value = result.item.id; productDialog.value = false
    noticeType.value = 'success'; notice.value = 'Product saved. You can now select multiple posts.'
  } catch (error:any) { noticeType.value = 'error'; notice.value = error?.data?.message || 'Unable to save product.' }
  finally { saving.value = false }
}
async function bindSelected() {
  const product = selectedProduct.value
  const sourceIds=triggerType.value==='post'?selectedPosts.value:selectedAds.value
  if (!product || !flowId.value || !sourceIds.length) return
  saving.value = true; notice.value = ''
  try {
    const items = sourceIds.map(sourceId => ({ pageId:pageId.value, sourceId, sourceType:triggerType.value, productId:product.id, flowId:flowId.value }))
    const result = await $fetch<{count:number}>('/api/proxy/api/v1/meta/product-bindings/batch', { method:'POST', body:{items} })
    await refreshBindings(); selectedPosts.value = []; selectedAds.value=[]
    noticeType.value = 'success'; notice.value = `Connected ${result.count} ${triggerType.value}${result.count===1?'':'s'} successfully.`
  } catch (error:any) { noticeType.value = 'error'; notice.value = error?.data?.message || 'Unable to create all automations.' }
  finally { saving.value = false }
}
watch(pageId, loadPosts)
watch(adAccountId,loadCampaigns);watch(triggerType,value=>{if(value==='ad'&&!adAccounts.value.length)loadAdAccounts()})
if (pageId.value) await loadPosts()
</script>

<template>
  <section class="hero"><div><p>PRODUCT AUTOMATION</p><h2>Build campaign and post automations</h2><span>Choose triggers, attach a product, and control the complete reply sequence in four guided steps.</span></div><v-chip color="success" variant="tonal" prepend-icon="mdi-lightning-bolt">First-message reply</v-chip></section>
  <v-alert v-if="notice" :type="noticeType" variant="tonal" closable class="mb-4" @click:close="notice=''">{{ notice }}</v-alert>
  <nav class="wizard-progress" aria-label="Automation setup progress"><button v-for="item in [{n:1,label:'Triggers'},{n:2,label:'Product'},{n:3,label:'Messages'},{n:4,label:'Review'}]" :key="item.n" :class="{active:currentStep===item.n,done:currentStep>item.n}" :disabled="item.n>currentStep" @click="currentStep=item.n"><span>{{currentStep>item.n?'✓':item.n}}</span><b>{{item.label}}</b></button></nav>
  <section v-show="currentStep===3" class="setup"><div class="step"><span>3</span><div><strong>Choose reply sequence</strong><small>Select an existing sequence or create a new one</small></div></div><v-select v-model="flowId" :items="flows" item-title="name" item-value="id" label="Automatic messages" :disabled="!flows.length" hide-details/><v-btn color="primary" variant="tonal" prepend-icon="mdi-message-plus-outline" @click="newFlow">Create messages</v-btn><div v-if="selectedFlow" class="preview"><strong>{{selectedFlow.name}}</strong><span>{{selectedFlow.messages.filter(message=>message.enabled).length}} active messages</span><small>{{selectedFlow.keywords.length?`Keywords: ${selectedFlow.keywords.join(', ')}`:'Replies to every attributed first message'}}</small></div></section>
  <section v-show="currentStep===2" class="setup"><div class="step"><span>2</span><div><strong>Choose product</strong><small>This product supplies details to the message sequence</small></div></div><v-select v-model="productId" :items="products" item-title="name" item-value="id" label="Product" :disabled="!products.length" hide-details/><v-btn color="primary" variant="tonal" prepend-icon="mdi-plus" @click="newProduct">Add product</v-btn><div v-if="selectedProduct" class="preview"><strong>{{selectedProduct.name}}</strong><span>{{selectedProduct.price}}</span><small>{{selectedProduct.description}}</small></div></section>
  <div v-show="currentStep===1" class="wizard-stage"><v-alert type="info" variant="tonal" class="mb-4">Choose the Page that receives messages, then select one or more campaigns. Every Ad ID inside them will be connected automatically.</v-alert>
  <section class="trigger-head"><div class="step"><span>1</span><div><strong>Select triggers</strong><small>Choose the campaigns or posts that start this automation</small></div></div><v-btn-toggle v-model="triggerType" mandatory color="primary"><v-btn value="post" prepend-icon="mdi-post-outline">Posts</v-btn><v-btn value="ad" prepend-icon="mdi-bullhorn-outline">Campaign Ads</v-btn></v-btn-toggle></section>
  <section v-if="triggerType==='post'" class="toolbar"><v-select v-model="pageId" :items="pages" item-title="name" item-value="id" label="Facebook Page" prepend-inner-icon="mdi-facebook" hide-details/><v-btn color="primary" variant="tonal" prepend-icon="mdi-refresh" :loading="loadingPosts" :disabled="!pageId" @click="loadPosts">Refresh</v-btn></section>
  <section v-else class="ad-filters"><v-select v-model="pageId" :items="pages" item-title="name" item-value="id" label="Page receiving messages" prepend-inner-icon="mdi-facebook" hide-details/><v-select v-model="adAccountId" :items="adAccountOptions" item-title="displayName" item-value="id" label="Ad Account" :loading="loadingAds" hide-details/><v-btn color="primary" variant="tonal" prepend-icon="mdi-refresh" :loading="loadingAds" @click="loadAdAccounts">Reload campaigns</v-btn><div v-if="selectedAdAccount" class="account-kind"><v-chip :color="selectedAdAccount.accountType==='business'?'primary':'success'" variant="tonal" :prepend-icon="selectedAdAccount.accountType==='business'?'mdi-domain':'mdi-account-circle-outline'">{{selectedAdAccount.accountType==='business'?'Business Account':'Personal Account'}}</v-chip><span v-if="selectedAdAccount.accountType==='business'">Portfolio: <strong>{{selectedAdAccount.businessName||selectedAdAccount.businessId}}</strong></span><span v-else>Owned directly by your Facebook account</span><small>{{selectedAdAccount.id}}</small></div></section>
  <v-alert v-if="!pages.length" type="info" variant="tonal">Enable at least one Facebook Page first.</v-alert>
  <section v-if="triggerType==='post'" class="post-list" :aria-busy="loadingPosts"><v-skeleton-loader v-if="loadingPosts" v-for="i in 4" :key="i" type="list-item-avatar-three-line"/><label v-for="post in posts" v-else :key="post.id" class="post-row" :class="{ selected:selectedPosts.includes(post.id) }"><v-checkbox v-model="selectedPosts" :value="post.id" hide-details color="primary"/><v-img v-if="post.pictureUrl" :src="post.pictureUrl" width="76" height="76" cover class="thumb"/><div v-else class="thumb placeholder"><v-icon icon="mdi-post-outline"/></div><div class="post-copy"><strong>{{ post.message || 'Post without text' }}</strong><small>{{ new Date(post.createdTime).toLocaleDateString() }} · {{ post.id }}</small><v-chip v-if="bindingFor(post.id)" color="success" size="x-small" variant="tonal">Linked: {{ bindingFor(post.id)?.productName }}</v-chip></div><v-btn :href="post.permalinkUrl" target="_blank" variant="text" size="small" @click.stop>View</v-btn></label><v-alert v-if="!loadingPosts&&!posts.length" type="info" variant="tonal">No published posts were returned for this Page.</v-alert></section>
  <template v-else><section class="campaign-grid"><button v-for="campaign in campaigns" :key="campaign.id" class="campaign-card" :class="{selected:selectedCampaignIds.includes(campaign.id)}" @click="toggleCampaign(campaign.id)"><v-checkbox-btn :model-value="selectedCampaignIds.includes(campaign.id)" color="primary" @click.stop="toggleCampaign(campaign.id)"/><div><strong>{{campaign.name}}</strong><small>{{campaign.objective||'Campaign'}} · {{campaign.id}}</small></div><v-chip :color="campaign.effectiveStatus==='ACTIVE'?'success':'warning'" size="small" variant="tonal">{{campaign.effectiveStatus}}</v-chip><div class="campaign-counts"><span><b>{{campaign.adSetCount}}</b> Ad Sets</span><span><b>{{campaign.adCount}}</b> Ads</span></div><small>{{selectedCampaignIds.includes(campaign.id)?'Selected for this message sequence':'Tick to include this campaign'}}</small></button><v-alert v-if="!loadingAds&&!campaigns.length" type="info" variant="tonal">Choose an Ad Account to load campaigns.</v-alert></section><section v-if="selectedCampaignIds.length" class="post-list" :aria-busy="loadingAds"><v-skeleton-loader v-if="loadingAds" v-for="i in 3" :key="i" type="list-item-three-line"/><div v-for="ad in ads" v-else :key="ad.id" class="ad-row selected"><v-icon icon="mdi-check-circle" color="success"/><v-icon icon="mdi-bullhorn-outline" size="30" color="primary"/><div class="post-copy"><strong>{{ad.name}}</strong><small>Ad ID · {{ad.id}}</small></div><v-chip :color="ad.effectiveStatus==='ACTIVE'?'success':'warning'" size="small" variant="tonal">{{ad.effectiveStatus}}</v-chip></div><v-alert v-if="!loadingAds&&!ads.length" type="warning" variant="tonal">Selected campaigns have no ads available.</v-alert></section></template>
  </div>
  <section v-show="currentStep===4" class="review"><div class="review-title"><v-icon icon="mdi-check-decagram-outline" color="primary" size="34"/><div><h3>Review your automation</h3><p>Confirm everything before connecting it to Meta Ads.</p></div></div><div class="review-grid"><article><small>TRIGGERS</small><strong>{{triggerType==='ad'?`${selectedCampaignIds.length} Campaigns`:`${selectedCount} Posts`}}</strong><span>{{triggerType==='ad'?`${selectedCount} Ad IDs will be connected`:'Selected Facebook posts'}}</span></article><article><small>PRODUCT</small><strong>{{selectedProduct?.name}}</strong><span>{{selectedProduct?.price}}</span></article><article><small>MESSAGES</small><strong>{{selectedFlow?.name}}</strong><span>{{selectedFlow?.messages.filter(message=>message.enabled).length}} active steps</span></article><article><small>DESTINATION</small><strong>{{pages.find(page=>page.id===pageId)?.name}}</strong><span>Facebook Messenger</span></article></div><v-alert type="warning" variant="tonal">Customers receive this sequence only on their first attributed message matching the configured keywords.</v-alert></section>
  <section class="wizard-actions"><v-btn v-if="currentStep>1" variant="text" prepend-icon="mdi-arrow-left" @click="previousStep">Back</v-btn><span v-else/><v-btn v-if="currentStep<4" color="primary" size="large" append-icon="mdi-arrow-right" :disabled="!stepReady" @click="nextStep">Continue</v-btn><v-btn v-else color="primary" size="large" prepend-icon="mdi-link-variant" :loading="saving" @click="bindSelected">Confirm and connect</v-btn></section>
  <v-dialog v-model="productDialog" max-width="580"><v-card class="dialog-card"><v-card-title>Add product</v-card-title><v-card-text class="form"><v-text-field v-model="productForm.name" label="Product name" autofocus/><v-text-field v-model="productForm.price" label="Price" placeholder="e.g. 250,000 LAK"/><v-textarea v-model="productForm.description" label="Product details" rows="4" counter="500" maxlength="500"/></v-card-text><v-card-actions><v-btn variant="text" @click="productDialog=false">Cancel</v-btn><v-spacer/><v-btn color="primary" :loading="saving" :disabled="!productForm.name||!productForm.price" @click="saveProduct">Save product</v-btn></v-card-actions></v-card></v-dialog>
  <v-dialog v-model="flowDialog" max-width="760"><v-card class="dialog-card"><v-card-title>Create automatic message sequence</v-card-title><v-card-text class="form"><v-text-field v-model="flowForm.name" label="Sequence name" autofocus/><v-combobox v-model="flowForm.keywords" label="Customer keywords" hint="Type a word and press Enter, e.g. price, ລາຄາ, ราคา" persistent-hint chips closable-chips multiple/><v-alert type="info" variant="tonal" density="compact">Text variables: <code v-text="'{{product.name}}'"/>, <code v-text="'{{product.price}}'"/>, <code v-text="'{{product.description}}'"/>. Media must use a public HTTPS URL.</v-alert><div v-for="(message,index) in flowForm.messages" :key="index" class="message-step"><strong>{{index+1}}</strong><div class="message-editor"><div class="message-head"><v-text-field v-model="message.code" label="Code" density="compact" hide-details/><v-select v-model="message.type" :items="messageTypes" label="Type" density="compact" hide-details/><v-switch v-model="message.enabled" label="Send" color="success" hide-details/></div><v-textarea v-if="message.type==='text'" v-model="message.content" label="Message text" rows="2" hide-details/><v-text-field v-else v-model="message.content" :label="`${message.type} HTTPS URL`" prepend-inner-icon="mdi-link" hide-details/><div v-if="message.type!=='text'&&message.content" class="media-preview"><v-img v-if="message.type==='image'" :src="message.content" height="120" cover/><video v-else-if="message.type==='video'" :src="message.content" controls/><audio v-else :src="message.content" controls/></div></div><div><v-btn icon="mdi-arrow-up" size="x-small" variant="text" :disabled="index===0" @click="moveMessage(index,-1)"/><v-btn icon="mdi-arrow-down" size="x-small" variant="text" :disabled="index===flowForm.messages.length-1" @click="moveMessage(index,1)"/><v-btn icon="mdi-delete-outline" size="x-small" color="error" variant="text" :disabled="flowForm.messages.length===1" @click="flowForm.messages.splice(index,1)"/></div></div><v-btn variant="tonal" prepend-icon="mdi-plus" @click="addMessage">Add next message</v-btn></v-card-text><v-card-actions><v-btn variant="text" @click="flowDialog=false">Cancel</v-btn><v-spacer/><v-btn color="primary" :loading="saving" :disabled="!flowForm.name||flowForm.messages.some(message=>!message.code.trim()||!message.content.trim())" @click="saveFlow">Save sequence</v-btn></v-card-actions></v-card></v-dialog>
</template>

<style scoped>
.hero,.setup,.toolbar,.post-list,.savebar{background:var(--color-surface);border:1px solid var(--color-border);border-radius:var(--radius-lg)}.hero{display:flex;justify-content:space-between;gap:20px;padding:24px;margin-bottom:16px}.hero p{margin:0 0 7px;color:var(--color-primary);font-size:10px;font-weight:800;letter-spacing:.13em}.hero h2{margin:0 0 7px;font-size:24px}.hero span,.step small{color:var(--color-text-secondary);font-size:13px}.setup,.toolbar{display:grid;grid-template-columns:minmax(190px,.65fr) minmax(240px,1fr) auto;gap:14px;align-items:center;padding:16px;margin-bottom:16px}.setup .preview{grid-column:2/-1;display:grid;padding:12px 14px;background:var(--color-background);border-radius:var(--radius-md)}.preview span{color:var(--color-primary);font-weight:700}.preview small{color:var(--color-text-secondary)}.step{display:flex;align-items:center;gap:10px}.step>span{display:grid;place-items:center;width:30px;height:30px;border-radius:50%;background:var(--color-primary);color:white;font-weight:800}.step>div{display:grid}.post-list{overflow:hidden}.post-row{display:grid;grid-template-columns:auto 76px 1fr auto;gap:14px;align-items:center;padding:14px 18px;border-bottom:1px solid var(--color-border-subtle);cursor:pointer;transition:.15s}.post-row:last-child{border-bottom:0}.post-row:hover,.post-row.selected{background:color-mix(in srgb,var(--color-primary) 7%,transparent)}.thumb{border-radius:10px}.placeholder{display:grid;place-items:center;background:var(--color-background)}.post-copy{display:grid;gap:5px;min-width:0}.post-copy strong{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.post-copy small{color:var(--color-text-muted)}.post-copy .v-chip{justify-self:start}.savebar{position:sticky;bottom:12px;display:flex;justify-content:space-between;align-items:center;gap:16px;padding:16px 20px;margin-top:16px;box-shadow:var(--shadow-lg);z-index:2}.dialog-card{border-radius:var(--radius-lg)!important}.form{display:grid;gap:4px;padding-top:18px!important}@media(max-width:760px){.hero,.savebar{display:grid}.setup,.toolbar{grid-template-columns:1fr}.setup .preview{grid-column:auto}.post-row{grid-template-columns:auto 56px 1fr}.post-row>.v-btn{display:none}}
.message-step{display:grid;grid-template-columns:28px 1fr auto;align-items:start;gap:10px;padding:12px;border:1px solid var(--color-border);border-radius:var(--radius-md)}.message-step>strong{display:grid;place-items:center;width:28px;height:28px;border-radius:50%;background:var(--color-primary);color:#fff}.message-step>div:last-child{display:grid}.message-editor{display:grid;gap:10px}.message-head{display:grid!important;grid-template-columns:1fr 150px auto;gap:10px}.media-preview{overflow:hidden;max-width:320px;border-radius:10px}.media-preview video{display:block;width:100%;max-height:180px}.media-preview audio{display:block;width:100%}.trigger-head{display:flex;justify-content:space-between;align-items:center;gap:16px;padding:16px;margin-bottom:12px;background:var(--color-surface);border:1px solid var(--color-border);border-radius:var(--radius-lg)}.ad-filters{display:grid;grid-template-columns:minmax(220px,1fr) minmax(220px,1fr) auto;gap:12px;padding:16px;margin-bottom:16px;background:var(--color-surface);border:1px solid var(--color-border);border-radius:var(--radius-lg)}.campaign-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin-bottom:16px}.campaign-card{display:grid;grid-template-columns:1fr auto;gap:12px;text-align:left;padding:18px;color:var(--color-text);background:var(--color-surface);border:1px solid var(--color-border);border-radius:var(--radius-lg);cursor:pointer}.campaign-card:hover,.campaign-card.selected{border-color:var(--color-primary);box-shadow:0 0 0 2px color-mix(in srgb,var(--color-primary) 18%,transparent)}.campaign-card>div:first-child{display:grid}.campaign-card small{color:var(--color-text-muted)}.campaign-counts{grid-column:1/-1;display:flex;gap:10px}.campaign-counts span{min-width:100px;padding:10px;border-radius:10px;background:var(--color-background);font-size:12px}.campaign-counts b{display:block;font-size:20px;color:var(--color-primary)}.ad-row{display:grid;grid-template-columns:auto 42px 1fr auto;align-items:center;gap:12px;padding:15px 18px;border-bottom:1px solid var(--color-border-subtle)}.ad-row.selected{background:color-mix(in srgb,var(--color-primary) 7%,transparent)}
.account-kind{grid-column:1/-1;display:flex;align-items:center;gap:12px;padding:12px 14px;background:var(--color-background);border-radius:var(--radius-md);font-size:13px}.account-kind small{margin-left:auto;color:var(--color-text-muted)}
.wizard-progress{display:grid;grid-template-columns:repeat(4,1fr);gap:0;margin-bottom:18px;padding:10px;background:var(--color-surface);border:1px solid var(--color-border);border-radius:var(--radius-lg)}.wizard-progress button{position:relative;display:flex;align-items:center;justify-content:center;gap:9px;padding:11px;color:var(--color-text-muted);background:none;border:0}.wizard-progress button:not(:last-child):after{content:"";position:absolute;right:-10%;width:20%;height:2px;background:var(--color-border)}.wizard-progress span{display:grid;place-items:center;width:28px;height:28px;border-radius:50%;background:var(--color-background);font-weight:800}.wizard-progress .active{color:var(--color-primary)}.wizard-progress .active span{color:white;background:var(--color-primary)}.wizard-progress .done{color:var(--color-success)}.wizard-progress .done span{color:white;background:var(--color-success)}.wizard-stage{min-height:320px}.wizard-actions{display:flex;justify-content:space-between;align-items:center;margin-top:18px;padding:16px 20px;background:var(--color-surface);border:1px solid var(--color-border);border-radius:var(--radius-lg);box-shadow:var(--shadow-md)}.review{display:grid;gap:18px;padding:24px;background:var(--color-surface);border:1px solid var(--color-border);border-radius:var(--radius-lg)}.review-title{display:flex;align-items:center;gap:13px}.review-title h3,.review-title p{margin:0}.review-title p{color:var(--color-text-secondary)}.review-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.review-grid article{display:grid;gap:5px;padding:18px;background:var(--color-background);border-radius:var(--radius-md)}.review-grid small{font-size:10px;font-weight:800;letter-spacing:.1em;color:var(--color-primary)}.review-grid strong{font-size:16px}.review-grid span{font-size:13px;color:var(--color-text-secondary)}@media(max-width:760px){.wizard-progress b{display:none}.review-grid{grid-template-columns:1fr}}
</style>
